name: 🐞 Bug Report
description: "Create a report to help us improve."
labels: [bug]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Welcome
      options:
        - label: Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golines/releases). Only such installations are supported.
          required: true
        - label: Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golines/issues) and didn't find any.
          required: true
        - label: I agree to follow this project's [Code of Conduct](https://github.com/golangci/golines?tab=coc-ov-file)
          required: true

  - type: dropdown
    id: install
    attributes:
      label: How did you install golines?
      options:
        - I don't know
        - Official binary
        - Brew
        - MacPorts
        - Chocolatey
        - Scoop
        - Docker
        - go install
        - Tools pattern
        - go tool
        - AUR
        - Nix
        - Deb
        - RPM
        - Other Linux package manager
        - Via editor/IDE
        - asdf/mise-en-place
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Description of the problem
      placeholder: Your problem description
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version of golines
      value: |-
        <details>

        ```console
        $ golines --version
        # Paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: go-env
    attributes:
      label: Go environment
      value: |-
        <details>

        ```console
        $ go version && go env
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: A minimal reproducible example or link to a public repository
      description: if your problem is related to a private repository, a minimal reproducible example is required.
      value: |-
        <details>

        ```go
        // add your code here
        ```

        </details>
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
        - label: Yes, I've included all the information above (version, etc.).
          required: true

  - type: checkboxes
    id: supporter
    attributes:
      label: Supporter
      options:
        - label: I am a [sponsor/backer](https://golangci-lint.run/docs/donate/)
