blank_issues_enabled: false
contact_links:
  - name:  Feature request
    url: https://github.com/golangci/golines/discussions/new?category=ideas
    about: Suggest an idea for this project.
  - name: ❓ Questions
    url: https://github.com/golangci/golines/discussions/new?category=q-a
    about: If you have a question or are looking for advice, please post on our Discussions forum!
